/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dsib1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "Carrier.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_ul_carrier_freq_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dl_carrier_freq_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_band_info_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ul_carrier_freq_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_dl_carrier_freq_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_band_info_value2enum_2[] = {
	{ 0,	5,	"band0" },
	{ 1,	5,	"band1" },
	{ 2,	5,	"band2" },
	{ 3,	5,	"band3" },
	{ 4,	5,	"band4" },
	{ 5,	5,	"band5" },
	{ 6,	5,	"band6" },
	{ 7,	5,	"band7" }
};
static const unsigned int asn_MAP_band_info_enum2value_2[] = {
	0,	/* band0(0) */
	1,	/* band1(1) */
	2,	/* band2(2) */
	3,	/* band3(3) */
	4,	/* band4(4) */
	5,	/* band5(5) */
	6,	/* band6(6) */
	7	/* band7(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_band_info_specs_2 = {
	asn_MAP_band_info_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_band_info_enum2value_2,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_band_info_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_band_info_2 = {
	"band-info",
	"band-info",
	&asn_OP_NativeEnumerated,
	asn_DEF_band_info_tags_2,
	sizeof(asn_DEF_band_info_tags_2)
		/sizeof(asn_DEF_band_info_tags_2[0]) - 1, /* 1 */
	asn_DEF_band_info_tags_2,	/* Same as above */
	sizeof(asn_DEF_band_info_tags_2)
		/sizeof(asn_DEF_band_info_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_band_info_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_band_info_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Carrier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Carrier, band_info),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_band_info_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"band-info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Carrier, ul_carrier_freq),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ul_carrier_freq_constr_11,  memb_ul_carrier_freq_constraint_1 },
		0, 0, /* No default value */
		"ul-carrier-freq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Carrier, dl_carrier_freq),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_dl_carrier_freq_constr_12,  memb_dl_carrier_freq_constraint_1 },
		0, 0, /* No default value */
		"dl-carrier-freq"
		},
};
static const ber_tlv_tag_t asn_DEF_Carrier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Carrier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* band-info */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ul-carrier-freq */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dl-carrier-freq */
};
asn_SEQUENCE_specifics_t asn_SPC_Carrier_specs_1 = {
	sizeof(struct Carrier),
	offsetof(struct Carrier, _asn_ctx),
	asn_MAP_Carrier_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Carrier = {
	"Carrier",
	"Carrier",
	&asn_OP_SEQUENCE,
	asn_DEF_Carrier_tags_1,
	sizeof(asn_DEF_Carrier_tags_1)
		/sizeof(asn_DEF_Carrier_tags_1[0]), /* 1 */
	asn_DEF_Carrier_tags_1,	/* Same as above */
	sizeof(asn_DEF_Carrier_tags_1)
		/sizeof(asn_DEF_Carrier_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Carrier_1,
	3,	/* Elements count */
	&asn_SPC_Carrier_specs_1	/* Additional specs */
};

