/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "LogicChannelConfig.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_priority_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_channel_type_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_priority_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_channel_type_value2enum_4[] = {
	{ 0,	4,	"ccch" },
	{ 1,	4,	"dtch" }
};
static const unsigned int asn_MAP_channel_type_enum2value_4[] = {
	0,	/* ccch(0) */
	1	/* dtch(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_channel_type_specs_4 = {
	asn_MAP_channel_type_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_channel_type_enum2value_4,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_channel_type_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_channel_type_4 = {
	"channel-type",
	"channel-type",
	&asn_OP_NativeEnumerated,
	asn_DEF_channel_type_tags_4,
	sizeof(asn_DEF_channel_type_tags_4)
		/sizeof(asn_DEF_channel_type_tags_4[0]) - 1, /* 1 */
	asn_DEF_channel_type_tags_4,	/* Same as above */
	sizeof(asn_DEF_channel_type_tags_4)
		/sizeof(asn_DEF_channel_type_tags_4[0]), /* 2 */
	{ 0, &asn_PER_type_channel_type_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_channel_type_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LogicChannelConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogicChannelConfig, logicch_id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LOGICCHENNEL_Identity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicch-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogicChannelConfig, priority),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_priority_constr_3,  memb_priority_constraint_1 },
		0, 0, /* No default value */
		"priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogicChannelConfig, channel_type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_channel_type_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channel-type"
		},
};
static const ber_tlv_tag_t asn_DEF_LogicChannelConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogicChannelConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* logicch-id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* priority */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* channel-type */
};
asn_SEQUENCE_specifics_t asn_SPC_LogicChannelConfig_specs_1 = {
	sizeof(struct LogicChannelConfig),
	offsetof(struct LogicChannelConfig, _asn_ctx),
	asn_MAP_LogicChannelConfig_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LogicChannelConfig = {
	"LogicChannelConfig",
	"LogicChannelConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_LogicChannelConfig_tags_1,
	sizeof(asn_DEF_LogicChannelConfig_tags_1)
		/sizeof(asn_DEF_LogicChannelConfig_tags_1[0]), /* 1 */
	asn_DEF_LogicChannelConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogicChannelConfig_tags_1)
		/sizeof(asn_DEF_LogicChannelConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LogicChannelConfig_1,
	3,	/* Elements count */
	&asn_SPC_LogicChannelConfig_specs_1	/* Additional specs */
};

