/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "RLC-Config.h"

asn_per_constraints_t asn_PER_type_RLC_Config_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_am_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_Config__am, ul_am_rlc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_AM_RLC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-am-rlc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_Config__am, dl_am_rlc),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_AM_RLC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-am-rlc"
		},
};
static const ber_tlv_tag_t asn_DEF_am_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_am_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-am-rlc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* dl-am-rlc */
};
static asn_SEQUENCE_specifics_t asn_SPC_am_specs_2 = {
	sizeof(struct RLC_Config__am),
	offsetof(struct RLC_Config__am, _asn_ctx),
	asn_MAP_am_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_am_2 = {
	"am",
	"am",
	&asn_OP_SEQUENCE,
	asn_DEF_am_tags_2,
	sizeof(asn_DEF_am_tags_2)
		/sizeof(asn_DEF_am_tags_2[0]) - 1, /* 1 */
	asn_DEF_am_tags_2,	/* Same as above */
	sizeof(asn_DEF_am_tags_2)
		/sizeof(asn_DEF_am_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_am_2,
	2,	/* Elements count */
	&asn_SPC_am_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_um_bi_direction_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_Config__um_bi_direction, ul_um_rlc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_UM_RLC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-um-rlc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_Config__um_bi_direction, dl_um_rlc),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_UM_RLC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-um-rlc"
		},
};
static const ber_tlv_tag_t asn_DEF_um_bi_direction_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_um_bi_direction_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-um-rlc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* dl-um-rlc */
};
static asn_SEQUENCE_specifics_t asn_SPC_um_bi_direction_specs_5 = {
	sizeof(struct RLC_Config__um_bi_direction),
	offsetof(struct RLC_Config__um_bi_direction, _asn_ctx),
	asn_MAP_um_bi_direction_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_um_bi_direction_5 = {
	"um-bi-direction",
	"um-bi-direction",
	&asn_OP_SEQUENCE,
	asn_DEF_um_bi_direction_tags_5,
	sizeof(asn_DEF_um_bi_direction_tags_5)
		/sizeof(asn_DEF_um_bi_direction_tags_5[0]) - 1, /* 1 */
	asn_DEF_um_bi_direction_tags_5,	/* Same as above */
	sizeof(asn_DEF_um_bi_direction_tags_5)
		/sizeof(asn_DEF_um_bi_direction_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_um_bi_direction_5,
	2,	/* Elements count */
	&asn_SPC_um_bi_direction_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RLC_Config_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_Config, choice.am),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_am_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"am"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_Config, choice.um_bi_direction),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_um_bi_direction_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"um-bi-direction"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RLC_Config_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* am */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* um-bi-direction */
};
asn_CHOICE_specifics_t asn_SPC_RLC_Config_specs_1 = {
	sizeof(struct RLC_Config),
	offsetof(struct RLC_Config, _asn_ctx),
	offsetof(struct RLC_Config, present),
	sizeof(((struct RLC_Config *)0)->present),
	asn_MAP_RLC_Config_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RLC_Config = {
	"RLC-Config",
	"RLC-Config",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_RLC_Config_constr_1, CHOICE_constraint },
	asn_MBR_RLC_Config_1,
	2,	/* Elements count */
	&asn_SPC_RLC_Config_specs_1	/* Additional specs */
};

