/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dccch.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "RRCConnectionSetup.h"

asn_TYPE_member_t asn_MBR_RRCConnectionSetup_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetup, radioResourceConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceConfigDedicate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioResourceConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetup, mac_config),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MacConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mac-config"
		},
	{ ATF_POINTER, 3, offsetof(struct RRCConnectionSetup, srb_ToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRB_ToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srb-ToAddModList"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCConnectionSetup, drb_ToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToAddModList"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetup, drb_ToReleaselist),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToReleaseList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToReleaselist"
		},
};
static const int asn_MAP_RRCConnectionSetup_oms_1[] = { 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_RRCConnectionSetup_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCConnectionSetup_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radioResourceConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mac-config */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* srb-ToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* drb-ToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* drb-ToReleaselist */
};
asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionSetup_specs_1 = {
	sizeof(struct RRCConnectionSetup),
	offsetof(struct RRCConnectionSetup, _asn_ctx),
	asn_MAP_RRCConnectionSetup_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RRCConnectionSetup_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetup = {
	"RRCConnectionSetup",
	"RRCConnectionSetup",
	&asn_OP_SEQUENCE,
	asn_DEF_RRCConnectionSetup_tags_1,
	sizeof(asn_DEF_RRCConnectionSetup_tags_1)
		/sizeof(asn_DEF_RRCConnectionSetup_tags_1[0]), /* 1 */
	asn_DEF_RRCConnectionSetup_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCConnectionSetup_tags_1)
		/sizeof(asn_DEF_RRCConnectionSetup_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRCConnectionSetup_1,
	5,	/* Elements count */
	&asn_SPC_RRCConnectionSetup_specs_1	/* Additional specs */
};

