/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectionrelease.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "RRCConnectionRelease.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_ue_Identity_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_releaseCause_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ue_Identity_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_releaseCause_value2enum_3[] = {
	{ 0,	6,	"normal" },
	{ 1,	5,	"other" }
};
static const unsigned int asn_MAP_releaseCause_enum2value_3[] = {
	0,	/* normal(0) */
	1	/* other(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_releaseCause_specs_3 = {
	asn_MAP_releaseCause_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_releaseCause_enum2value_3,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_releaseCause_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_releaseCause_3 = {
	"releaseCause",
	"releaseCause",
	&asn_OP_NativeEnumerated,
	asn_DEF_releaseCause_tags_3,
	sizeof(asn_DEF_releaseCause_tags_3)
		/sizeof(asn_DEF_releaseCause_tags_3[0]) - 1, /* 1 */
	asn_DEF_releaseCause_tags_3,	/* Same as above */
	sizeof(asn_DEF_releaseCause_tags_3)
		/sizeof(asn_DEF_releaseCause_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_releaseCause_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_releaseCause_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRCConnectionRelease_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionRelease, ue_Identity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ue_Identity_constr_2,  memb_ue_Identity_constraint_1 },
		0, 0, /* No default value */
		"ue-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionRelease, releaseCause),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_releaseCause_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"releaseCause"
		},
};
static const ber_tlv_tag_t asn_DEF_RRCConnectionRelease_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCConnectionRelease_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-Identity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* releaseCause */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRelease_specs_1 = {
	sizeof(struct RRCConnectionRelease),
	offsetof(struct RRCConnectionRelease, _asn_ctx),
	asn_MAP_RRCConnectionRelease_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease = {
	"RRCConnectionRelease",
	"RRCConnectionRelease",
	&asn_OP_SEQUENCE,
	asn_DEF_RRCConnectionRelease_tags_1,
	sizeof(asn_DEF_RRCConnectionRelease_tags_1)
		/sizeof(asn_DEF_RRCConnectionRelease_tags_1[0]), /* 1 */
	asn_DEF_RRCConnectionRelease_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCConnectionRelease_tags_1)
		/sizeof(asn_DEF_RRCConnectionRelease_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRCConnectionRelease_1,
	2,	/* Elements count */
	&asn_SPC_RRCConnectionRelease_specs_1	/* Additional specs */
};

