/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "SRB-ToAddMod.h"

asn_TYPE_member_t asn_MBR_SRB_ToAddMod_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SRB_ToAddMod, srb_Identity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRB_Identity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srb-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRB_ToAddMod, rlc_config),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RLC_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlc-config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRB_ToAddMod, logicChannelConfig),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicChannelConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicChannelConfig"
		},
};
static const ber_tlv_tag_t asn_DEF_SRB_ToAddMod_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SRB_ToAddMod_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* srb-Identity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rlc-config */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* logicChannelConfig */
};
asn_SEQUENCE_specifics_t asn_SPC_SRB_ToAddMod_specs_1 = {
	sizeof(struct SRB_ToAddMod),
	offsetof(struct SRB_ToAddMod, _asn_ctx),
	asn_MAP_SRB_ToAddMod_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SRB_ToAddMod = {
	"SRB-ToAddMod",
	"SRB-ToAddMod",
	&asn_OP_SEQUENCE,
	asn_DEF_SRB_ToAddMod_tags_1,
	sizeof(asn_DEF_SRB_ToAddMod_tags_1)
		/sizeof(asn_DEF_SRB_ToAddMod_tags_1[0]), /* 1 */
	asn_DEF_SRB_ToAddMod_tags_1,	/* Same as above */
	sizeof(asn_DEF_SRB_ToAddMod_tags_1)
		/sizeof(asn_DEF_SRB_ToAddMod_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SRB_ToAddMod_1,
	3,	/* Elements count */
	&asn_SPC_SRB_ToAddMod_specs_1	/* Additional specs */
};

