/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dsib1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#include "UlRefSigConfig-PUSCH.h"

static int
memb_group_assign_pusch_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 29)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_cycle_shift_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_group_assign_pusch_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  29 }	/* (0..29) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_cycle_shift_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_UlRefSigConfig_PUSCH_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UlRefSigConfig_PUSCH, group_hopping_enable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"group-hopping-enable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UlRefSigConfig_PUSCH, seq_hopping_enable),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"seq-hopping-enable"
		},
	{ ATF_POINTER, 2, offsetof(struct UlRefSigConfig_PUSCH, group_assign_pusch),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_group_assign_pusch_constr_4,  memb_group_assign_pusch_constraint_1 },
		0, 0, /* No default value */
		"group-assign-pusch"
		},
	{ ATF_POINTER, 1, offsetof(struct UlRefSigConfig_PUSCH, cycle_shift),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_cycle_shift_constr_5,  memb_cycle_shift_constraint_1 },
		0, 0, /* No default value */
		"cycle-shift"
		},
};
static const int asn_MAP_UlRefSigConfig_PUSCH_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_UlRefSigConfig_PUSCH_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UlRefSigConfig_PUSCH_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* group-hopping-enable */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* seq-hopping-enable */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* group-assign-pusch */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* cycle-shift */
};
asn_SEQUENCE_specifics_t asn_SPC_UlRefSigConfig_PUSCH_specs_1 = {
	sizeof(struct UlRefSigConfig_PUSCH),
	offsetof(struct UlRefSigConfig_PUSCH, _asn_ctx),
	asn_MAP_UlRefSigConfig_PUSCH_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_UlRefSigConfig_PUSCH_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UlRefSigConfig_PUSCH = {
	"UlRefSigConfig-PUSCH",
	"UlRefSigConfig-PUSCH",
	&asn_OP_SEQUENCE,
	asn_DEF_UlRefSigConfig_PUSCH_tags_1,
	sizeof(asn_DEF_UlRefSigConfig_PUSCH_tags_1)
		/sizeof(asn_DEF_UlRefSigConfig_PUSCH_tags_1[0]), /* 1 */
	asn_DEF_UlRefSigConfig_PUSCH_tags_1,	/* Same as above */
	sizeof(asn_DEF_UlRefSigConfig_PUSCH_tags_1)
		/sizeof(asn_DEF_UlRefSigConfig_PUSCH_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UlRefSigConfig_PUSCH_1,
	4,	/* Elements count */
	&asn_SPC_UlRefSigConfig_PUSCH_specs_1	/* Additional specs */
};

