/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_DRB_ToAddMod_H_
#define	_DRB_ToAddMod_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-Identity.h"
#include "RLC-Config.h"
#include "LogicChannelConfig.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DRB-ToAddMod */
typedef struct DRB_ToAddMod {
	DRB_Identity_t	 drb_Identity;
	RLC_Config_t	 rlc_config;
	LogicChannelConfig_t	 logicChannelConfig;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_ToAddMod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRB_ToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_DRB_ToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_DRB_ToAddMod_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DRB_ToAddMod_H_ */
#include <asn_internal.h>
