/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_LOGICCHENNEL_Identity_H_
#define	_LOGICCHENNEL_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LOGICCHENNEL-Identity */
typedef long	 LOGICCHENNEL_Identity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LOGICCHENNEL_Identity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LOGICCHENNEL_Identity;
asn_struct_free_f LOGICCHENNEL_Identity_free;
asn_struct_print_f LOGICCHENNEL_Identity_print;
asn_constr_check_f LOGICCHENNEL_Identity_constraint;
ber_type_decoder_f LOGICCHENNEL_Identity_decode_ber;
der_type_encoder_f LOGICCHENNEL_Identity_encode_der;
xer_type_decoder_f LOGICCHENNEL_Identity_decode_xer;
xer_type_encoder_f LOGICCHENNEL_Identity_encode_xer;
per_type_decoder_f LOGICCHENNEL_Identity_decode_uper;
per_type_encoder_f LOGICCHENNEL_Identity_encode_uper;
per_type_decoder_f LOGICCHENNEL_Identity_decode_aper;
per_type_encoder_f LOGICCHENNEL_Identity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LOGICCHENNEL_Identity_H_ */
#include <asn_internal.h>
