/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_LogicChannelConfig_H_
#define	_LogicChannelConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LOGICCHENNEL-Identity.h"
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LogicChannelConfig__channel_type {
	LogicChannelConfig__channel_type_ccch	= 0,
	LogicChannelConfig__channel_type_dtch	= 1
} e_LogicChannelConfig__channel_type;

/* LogicChannelConfig */
typedef struct LogicChannelConfig {
	LOGICCHENNEL_Identity_t	 logicch_id;
	long	 priority;
	long	 channel_type;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogicChannelConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_channel_type_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LogicChannelConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_LogicChannelConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_LogicChannelConfig_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LogicChannelConfig_H_ */
#include <asn_internal.h>
