/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_MacConfig_H_
#define	_MacConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MacConfig */
typedef struct MacConfig {
	long	 maxharq_tx;
	long	 max_out_sync;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MacConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MacConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_MacConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_MacConfig_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MacConfig_H_ */
#include <asn_internal.h>
