/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_PdschDedicateConfig_H_
#define	_PdschDedicateConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PdschDedicateConfig */
typedef struct PdschDedicateConfig {
	long	 c_rnti;
	long	 beta_off_ack_ind;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PdschDedicateConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PdschDedicateConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_PdschDedicateConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_PdschDedicateConfig_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PdschDedicateConfig_H_ */
#include <asn_internal.h>
