/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dsib1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_PuschHoppingConfig_H_
#define	_PuschHoppingConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PuschHoppingConfig__hop_mode {
	PuschHoppingConfig__hop_mode_inter	= 0,
	PuschHoppingConfig__hop_mode_interandintra	= 1
} e_PuschHoppingConfig__hop_mode;

/* PuschHoppingConfig */
typedef struct PuschHoppingConfig {
	BOOLEAN_t	 hop_enable;
	long	*hop_mode;	/* OPTIONAL */
	long	*hop_offset;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PuschHoppingConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_hop_mode_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PuschHoppingConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_PuschHoppingConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_PuschHoppingConfig_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PuschHoppingConfig_H_ */
#include <asn_internal.h>
