/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_RadioResourceConfigDedicate_H_
#define	_RadioResourceConfigDedicate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PdschDedicateConfig.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioResourceConfigDedicate */
typedef struct RadioResourceConfigDedicate {
	PdschDedicateConfig_t	 pusch_dedi_config;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioResourceConfigDedicate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigDedicate;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigDedicate_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioResourceConfigDedicate_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RadioResourceConfigDedicate_H_ */
#include <asn_internal.h>
