/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dulccch.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_RCConnectionComplete_H_
#define	_RCConnectionComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RCConnectionComplete */
typedef struct RCConnectionComplete {
	BOOLEAN_t	 complete_status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RCConnectionComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RCConnectionComplete;
extern asn_SEQUENCE_specifics_t asn_SPC_RCConnectionComplete_specs_1;
extern asn_TYPE_member_t asn_MBR_RCConnectionComplete_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RCConnectionComplete_H_ */
#include <asn_internal.h>
