/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dccch.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_RRCConnectionRequest_H_
#define	_RRCConnectionRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionRequest__establishmentCause {
	RRCConnectionRequest__establishmentCause_normal	= 0,
	RRCConnectionRequest__establishmentCause_emergency	= 1
} e_RRCConnectionRequest__establishmentCause;

/* RRCConnectionRequest */
typedef struct RRCConnectionRequest {
	long	 ue_Identity;
	BIT_STRING_t	 ue_Ip;
	long	 establishmentCause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRequest_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_establishmentCause_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRequest_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionRequest_H_ */
#include <asn_internal.h>
