/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dccch.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_RRCConnectionComplete_H_
#define	_RRCConnectionComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionComplete */
typedef struct RRCConnectionComplete {
	BOOLEAN_t	 complete_status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionComplete;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionComplete_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionComplete_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionComplete_H_ */
#include <asn_internal.h>
