/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dccch.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_RRCConnectionSetup_H_
#define	_RRCConnectionSetup_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioResourceConfigDedicate.h"
#include "MacConfig.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SRB_ToAddModList;
struct DRB_ToAddModList;
struct DRB_ToReleaseList;

/* RRCConnectionSetup */
typedef struct RRCConnectionSetup {
	RadioResourceConfigDedicate_t	 radioResourceConfigCommon;
	MacConfig_t	 mac_config;
	struct SRB_ToAddModList	*srb_ToAddModList;	/* OPTIONAL */
	struct DRB_ToAddModList	*drb_ToAddModList;	/* OPTIONAL */
	struct DRB_ToReleaseList	*drb_ToReleaselist;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionSetup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetup;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionSetup_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionSetup_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SRB-ToAddModList.h"
#include "DRB-ToAddModList.h"
#include "DRB-ToReleaseList.h"

#endif	/* _RRCConnectionSetup_H_ */
#include <asn_internal.h>
