/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectionrelease.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_RRCConnectionRelease_H_
#define	_RRCConnectionRelease_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionRelease__releaseCause {
	RRCConnectionRelease__releaseCause_normal	= 0,
	RRCConnectionRelease__releaseCause_other	= 1
} e_RRCConnectionRelease__releaseCause;

/* RRCConnectionRelease */
typedef struct RRCConnectionRelease {
	long	 ue_Identity;
	long	 releaseCause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_releaseCause_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionRelease_H_ */
#include <asn_internal.h>
