/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dconnectsetup.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_SRB_ToAddMod_H_
#define	_SRB_ToAddMod_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRB-Identity.h"
#include "RLC-Config.h"
#include "LogicChannelConfig.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SRB-ToAddMod */
typedef struct SRB_ToAddMod {
	SRB_Identity_t	 srb_Identity;
	RLC_Config_t	 rlc_config;
	LogicChannelConfig_t	 logicChannelConfig;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SRB_ToAddMod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRB_ToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_SRB_ToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_SRB_ToAddMod_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SRB_ToAddMod_H_ */
#include <asn_internal.h>
