/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dsib1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_SystemInformationBlockType1_H_
#define	_SystemInformationBlockType1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "P-Max.h"
#include "TDD-Config.h"
#include "Carrier.h"
#include "RadioResourceConfigCommonSIB.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SystemInformationBlockType1 */
typedef struct SystemInformationBlockType1 {
	P_Max_t	 p_Max;
	TDD_Config_t	 tdd_Config;
	Carrier_t	 carrierFreq_info;
	RadioResourceConfigCommonSIB_t	 radioResourceConfigCommon;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationBlockType1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType1;

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformationBlockType1_H_ */
#include <asn_internal.h>
