/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "d2dsib1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_UlRefSigConfig_PUSCH_H_
#define	_UlRefSigConfig_PUSCH_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UlRefSigConfig-PUSCH */
typedef struct UlRefSigConfig_PUSCH {
	BOOLEAN_t	 group_hopping_enable;
	BOOLEAN_t	 seq_hopping_enable;
	long	*group_assign_pusch;	/* OPTIONAL */
	long	*cycle_shift;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UlRefSigConfig_PUSCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UlRefSigConfig_PUSCH;
extern asn_SEQUENCE_specifics_t asn_SPC_UlRefSigConfig_PUSCH_specs_1;
extern asn_TYPE_member_t asn_MBR_UlRefSigConfig_PUSCH_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UlRefSigConfig_PUSCH_H_ */
#include <asn_internal.h>
